//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProjectoFinal_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Documento = new HashSet<Documento>();
        }
    
        public int ClientePK { get; set; }
        public string Nome { get; set; }
        public string Rua { get; set; }
        public string Localidade { get; set; }
        public string Pais { get; set; }
        public string CodigoPostal { get; set; }
        public string NIF { get; set; }
        public string Telefone { get; set; }
    
        public virtual ICollection<Documento> Documento { get; set; }
    }
}
