//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProjectoFinal_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.Linha = new HashSet<Linha>();
        }
    
        public int DocumentoPK { get; set; }
        public Nullable<int> SerieFK { get; set; }
        public Nullable<int> ClienteFK { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Serie Serie { get; set; }
        public virtual ICollection<Linha> Linha { get; set; }
    }
}
