//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProjectoFinal_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVA
    {
        public IVA()
        {
            this.Produto = new HashSet<Produto>();
        }
    
        public int IVAPK { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Taxa { get; set; }
    
        public virtual ICollection<Produto> Produto { get; set; }
    }
}
