//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProjectoFinal_03
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbProjectoFinal_03 : DbContext
    {
        public dbProjectoFinal_03()
            : base("name=dbProjectoFinal_03")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
    
        public virtual int procAdicionaCliente(string nome, string rua, string localidade, string codigoPostal, string pais, string nif, string telefone)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var ruaParameter = rua != null ?
                new ObjectParameter("rua", rua) :
                new ObjectParameter("rua", typeof(string));
    
            var localidadeParameter = localidade != null ?
                new ObjectParameter("localidade", localidade) :
                new ObjectParameter("localidade", typeof(string));
    
            var codigoPostalParameter = codigoPostal != null ?
                new ObjectParameter("codigoPostal", codigoPostal) :
                new ObjectParameter("codigoPostal", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var nifParameter = nif != null ?
                new ObjectParameter("nif", nif) :
                new ObjectParameter("nif", typeof(string));
    
            var telefoneParameter = telefone != null ?
                new ObjectParameter("telefone", telefone) :
                new ObjectParameter("telefone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procAdicionaCliente", nomeParameter, ruaParameter, localidadeParameter, codigoPostalParameter, paisParameter, nifParameter, telefoneParameter);
        }
    
        public virtual int procAlteraCliente(Nullable<int> clientePK, string nome, string rua, string localidade, string codigoPostal, string pais, string nif, string telefone)
        {
            var clientePKParameter = clientePK.HasValue ?
                new ObjectParameter("clientePK", clientePK) :
                new ObjectParameter("clientePK", typeof(int));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var ruaParameter = rua != null ?
                new ObjectParameter("rua", rua) :
                new ObjectParameter("rua", typeof(string));
    
            var localidadeParameter = localidade != null ?
                new ObjectParameter("localidade", localidade) :
                new ObjectParameter("localidade", typeof(string));
    
            var codigoPostalParameter = codigoPostal != null ?
                new ObjectParameter("codigoPostal", codigoPostal) :
                new ObjectParameter("codigoPostal", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var nifParameter = nif != null ?
                new ObjectParameter("nif", nif) :
                new ObjectParameter("nif", typeof(string));
    
            var telefoneParameter = telefone != null ?
                new ObjectParameter("telefone", telefone) :
                new ObjectParameter("telefone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procAlteraCliente", clientePKParameter, nomeParameter, ruaParameter, localidadeParameter, codigoPostalParameter, paisParameter, nifParameter, telefoneParameter);
        }
    
        public virtual int procEliminaCliente(Nullable<int> clientePK)
        {
            var clientePKParameter = clientePK.HasValue ?
                new ObjectParameter("clientePK", clientePK) :
                new ObjectParameter("clientePK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procEliminaCliente", clientePKParameter);
        }
    }
}
