//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProjectoFinal_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Linha = new HashSet<Linha>();
        }
    
        public int ProdutoPK { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Preço { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> IVAFK { get; set; }
    
        public virtual IVA IVA { get; set; }
        public virtual ICollection<Linha> Linha { get; set; }
    }
}
