//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webProjectoFinal_03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public Serie()
        {
            this.DetalheConta = new HashSet<DetalheConta>();
            this.Documento = new HashSet<Documento>();
        }
    
        public int SeriePK { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Numero { get; set; }
    
        public virtual ICollection<DetalheConta> DetalheConta { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
    }
}
